name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]
  schedule:
    # Every Saturday at 4:30 AM UTC.
    - cron:  '30 4 * * 6'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12, ubuntu-20.04, macos-11]

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Update Rust Toolchain
      run: rustup update
    - name: Install dependencies (macOS)
      run: brew install shunit2 shellcheck shfmt
      if: runner.os == 'macOS'
    - name: Install dependencies (Linux)
      run: |
        sudo apt-get update
        sudo apt-get -y install libacl1-dev acl shunit2 valgrind shellcheck
      if: runner.os == 'Linux'
    - name: Fetch
      run: cargo fetch
    - name: Build (no-serde)
      run: cargo build
    - name: Build (serde)
      run: cargo build --features serde
    - name: Unit Test (no-serde)
      run: cargo test
    - name: Unit Test (serde)
      run: RUST_LOG=debug cargo test --features serde
    - name: Run integration tests
      run: ./tests/run_tests.sh
    - name: Run memory tests (Linux)
      run: ./tests/run_tests.sh memcheck
      if: runner.os == 'Linux'
    - name: Run TMPFS tests (Linux)
      run: |
        mkdir /run/user/$UID/exacl
        export TMPDIR=/run/user/$UID/exacl
        RUST_LOG=debug cargo test --features serde
        ./tests/run_tests.sh
      if: runner.os == 'Linux'
    - name: Code coverage
      env:
        CODECOV_TOKEN: ${{ secrets.EXACL_CODECOV_TOKEN }}
      run: ./ci/coverage.sh codecov
    - name: Lint Check
      run: ./ci/lint.sh
    - name: Format Check
      run: ./ci/format.sh
    - name: Docs Check
      run: ./ci/docs.sh
    - name: Bindgen Check
      run: ./ci/bindgen.sh
